### ISSUE TITLE
PM Sensor currently read via USB

### ISSUE THREAD

**Issue by mrvisscher** [marc-vdm/PollutionPainter#2]
PM Sensor is currently read via USB, test whether it can directly be controlled via the Raspberry Pi.

**Comment by marc-vdm** [comment]
PM Sensor has `PWM` output for each `PM10` and `PM2.5` outputs (see the table on page 4 of [the pdf](https://github.com/marc-vdm/PollutionPainter/blob/main/Useful%20files/SDS011-DATASHEET.pdf)). 

[`PWM` cannot be read by Raspberry pi](https://raspberrypi.stackexchange.com/questions/9787/pwm-input-in-raspberry-pi)
